name: task_management_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  ionicons: 0.2.1
  iconsax: 0.0.8
  font_awesome_flutter: 10.2.1
  ant_design_flutter: 0.0.1+5
  firebase_core: 2.3.0
  firebase_auth: 4.1.4
  google_sign_in: 5.4.2
  firebase_auth_web: 5.1.3
  cloud_firestore: 4.1.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/
    - assets/icons/
  uses-material-design: true
