// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAR-C0AiQIz2wIssGWBwHKS_ySxVveVEd4',
    appId: '1:109600032828:web:07b2001e0af28928709b39',
    messagingSenderId: '109600032828',
    projectId: 'task-managementapps-48cd8',
    authDomain: 'task-managementapps-48cd8.firebaseapp.com',
    storageBucket: 'task-managementapps-48cd8.appspot.com',
    measurementId: 'G-D02FP5Q9R4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBc5mDMmeJP58qynDYQgOhA8AzlG7_tc5U',
    appId: '1:109600032828:android:c2f8ddbd3e536a2b709b39',
    messagingSenderId: '109600032828',
    projectId: 'task-managementapps-48cd8',
    storageBucket: 'task-managementapps-48cd8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBE3ncq4Klb6k61596ZmjY_2CNx7txcloI',
    appId: '1:109600032828:ios:d42779357dc39be2709b39',
    messagingSenderId: '109600032828',
    projectId: 'task-managementapps-48cd8',
    storageBucket: 'task-managementapps-48cd8.appspot.com',
    androidClientId:
        '109600032828-s0lg266ds0m5dba2ihp7hsf83583k99m.apps.googleusercontent.com',
    iosClientId:
        '109600032828-729itmnqgqcn1paben83o6p80242u9hl.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskManagementApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBE3ncq4Klb6k61596ZmjY_2CNx7txcloI',
    appId: '1:109600032828:ios:d42779357dc39be2709b39',
    messagingSenderId: '109600032828',
    projectId: 'task-managementapps-48cd8',
    storageBucket: 'task-managementapps-48cd8.appspot.com',
    androidClientId:
        '109600032828-s0lg266ds0m5dba2ihp7hsf83583k99m.apps.googleusercontent.com',
    iosClientId:
        '109600032828-729itmnqgqcn1paben83o6p80242u9hl.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskManagementApp',
  );
}
